services:

  taic-app:
    container_name: taic-app
    build: .
    volumes:
      - ./taic-app:/var/www/html
    ports:
      - 9000:80
  
  mysql_db:
    container_name: taic-db
    image: mysql:8.0.33
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taic_app
    ports:
    - 3366:3306
  
  phpmyadmin:
    container_name: taic-phpmyadmin
    image: phpmyadmin:5.2.1
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1
